.PHONY: install
install:
	@mkdir $(INSTALL_PATH)/include/cleri
	@cp ../inc/cleri/*.h $(INSTALL_PATH)/include/cleri/
	@cp $(FN).$(MAJOR).$(MINOR).$(PATCH) $(INSTALL_PATH)/lib/$(FN).$(MAJOR).$(MINOR).$(PATCH)
	@ln -s $(INSTALL_PATH)/lib/$(FN).$(MAJOR).$(MINOR).$(PATCH) $(INSTALL_PATH)/lib/$(FN).$(MAJOR)
	@ln -s $(INSTALL_PATH)/lib/$(FN).$(MAJOR) $(INSTALL_PATH)/lib/$(FN)

.PHONY: uninstall
uninstall:
	@rm -f $(INSTALL_PATH)/include/cleri/*.h
	@rmdir $(INSTALL_PATH)/include/cleri/
	@rm -f $(INSTALL_PATH)/lib/$(FN)
	@rm -f $(INSTALL_PATH)/lib/$(FN).$(MAJOR)
	@rm -f $(INSTALL_PATH)/lib/$(FN).$(MAJOR).$(MINOR).$(PATCH)

